"""Explicit, profile-scoped TUI adapter setup; importing this module is inert.

Usage: python widget_setup.py enable|disable [--json]
Only agy-plus-usage.mjs is managed; the companion agy-usage.mjs is untouched.
"""
from __future__ import annotations

import argparse
from contextlib import contextmanager
import hashlib
import json
import os
from pathlib import Path
import re
import secrets
import stat
import sys

OWNER = "antigravity-oauth-plus"
ADAPTER_NAME = "agy-plus-usage.mjs"
_HEADER = f"// Generated by {OWNER}; adapter-format=1. Do not edit.\n"
_MAX_ADAPTER = 16384


class SetupError(RuntimeError):
    """Setup refused an unsafe path, missing target, or unowned adapter."""


def _absolute(path: str | Path) -> Path:
    raw = os.fspath(path)
    value = Path(raw)
    if not raw or not value.is_absolute() or ".." in value.parts or value == Path(value.anchor):
        raise SetupError(f"Expected an absolute, non-root path without traversal: {raw!r}")
    return value


def _home() -> Path:
    # Resolve on every invocation, never at import or installation time.
    if "HERMES_HOME" in os.environ:
        return _absolute(os.environ["HERMES_HOME"])
    try:
        from hermes_constants import get_hermes_home
    except ImportError:
        return _absolute(Path.home() / ".hermes")
    return _absolute(get_hermes_home())


def _target(plugin_dir: str | Path | None) -> Path:
    root = _absolute(plugin_dir if plugin_dir is not None else Path(__file__).absolute().parent)
    target = root / "tui" / "agy-usage.mjs"
    if not target.is_relative_to(root):
        raise SetupError("Widget target escapes the plugin directory")
    return target


@contextmanager
def _directory(path: Path, *, create: bool = False):
    """Walk from the filesystem root using no-follow directory descriptors.

    Neither the profile root nor any existing ancestor may be a symlink.
    Descriptors anchor all subsequent operations, even if a pathname changes.
    """
    if not hasattr(os, "O_NOFOLLOW") or not hasattr(os, "O_DIRECTORY"):
        raise SetupError("Safe widget setup requires no-follow directory operations")
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
    fd = os.open(path.anchor, flags)
    try:
        for part in path.parts[1:]:
            if create:
                try:
                    os.mkdir(part, mode=0o700, dir_fd=fd)
                except FileExistsError:
                    pass
            next_fd = os.open(part, flags, dir_fd=fd)
            os.close(fd)
            fd = next_fd
        yield fd
    finally:
        os.close(fd)


def _read_regular(directory_fd: int, name: str, *, adapter: bool = False):
    flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK
    try:
        fd = os.open(name, flags, dir_fd=directory_fd)
    except FileNotFoundError:
        return None
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode) or (adapter and info.st_nlink != 1):
            raise SetupError(f"Not a normal {'unaliased adapter' if adapter else 'widget'} regular file: {name}")
        chunks = []
        size = 0
        while True:
            chunk = os.read(fd, 65536)
            if not chunk:
                break
            chunks.append(chunk)
            size += len(chunk)
            if adapter and size > _MAX_ADAPTER:
                raise SetupError("Adapter is too large to be generated by this setup")
        return b"".join(chunks), info
    finally:
        os.close(fd)


def _render(target: Path, version: str) -> bytes:
    uri = target.as_uri() + "?v=" + version
    export = f"export {{ default }} from {json.dumps(uri, ensure_ascii=True)};\n".encode("utf-8")
    seal = f"// adapter-sha256={hashlib.sha256(export).hexdigest()}\n"
    return _HEADER.encode("utf-8") + seal.encode("ascii") + export


def _owned(content: bytes, target: Path) -> bool:
    """Validate the complete generated format, target URI and version grammar.

    Old content hashes remain valid for disable/update after a plugin upgrade;
    an owner comment alone is never authorization to overwrite or remove.
    """
    try:
        text = content.decode("utf-8")
        if not text.startswith(_HEADER):
            return False
        seal, export = text[len(_HEADER):].split("\n", 1)
        if not re.fullmatch(r"// adapter-sha256=[0-9a-f]{64}", seal):
            return False
        if seal != "// adapter-sha256=" + hashlib.sha256(export.encode("utf-8")).hexdigest():
            return False
        prefix = "export { default } from "
        if not export.startswith(prefix) or not export.endswith(";\n"):
            return False
        uri = json.loads(export[len(prefix):-2])
        expected = target.as_uri() + "?v="
        if not isinstance(uri, str) or not uri.startswith(expected):
            return False
        version = uri[len(expected):]
        return bool(re.fullmatch(r"[0-9a-f]{64}", version)) and content == _render(target, version)
    except (UnicodeError, ValueError):
        return False


def _same_file(fd: int, name: str, previous) -> None:
    current = _read_regular(fd, name, adapter=True)
    if previous is None:
        if current is not None:
            raise SetupError("Adapter appeared during setup; refusing to overwrite")
    elif current is None or current[0] != previous[0] or (current[1].st_dev, current[1].st_ino) != (previous[1].st_dev, previous[1].st_ino):
        raise SetupError("Adapter changed during setup; refusing mutation")


def _publish(fd: int, content: bytes, previous) -> None:
    """Publish a private, fully flushed file atomically without clobbering races."""
    temporary = f".agy-plus-usage-{secrets.token_hex(16)}.tmp"
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW
    temp_fd = os.open(temporary, flags, mode=0o600, dir_fd=fd)
    try:
        try:
            os.fchmod(temp_fd, 0o600)
            view = memoryview(content)
            while view:
                written = os.write(temp_fd, view)
                if not written:
                    raise SetupError("Short write while creating adapter")
                view = view[written:]
            os.fsync(temp_fd)
        finally:
            os.close(temp_fd)
        _same_file(fd, ADAPTER_NAME, previous)
        if previous is None:
            # Unlike rename/replace, link atomically refuses an occupied leaf.
            os.link(temporary, ADAPTER_NAME, src_dir_fd=fd, dst_dir_fd=fd, follow_symlinks=False)
        else:
            os.replace(temporary, ADAPTER_NAME, src_dir_fd=fd, dst_dir_fd=fd)
    finally:
        try:
            os.unlink(temporary, dir_fd=fd)
        except FileNotFoundError:
            pass
        os.fsync(fd)


def _result(action: str, home: Path, changed: bool) -> dict:
    return {"ok": True, "action": action, "changed": changed, "home": str(home),
            "adapter": str(home / "tui-widgets" / ADAPTER_NAME)}


def enable(*, plugin_dir: str | Path | None = None) -> dict:
    """Enable for the call-time profile; plugin_dir is an optional fixture override."""
    try:
        home = _home()
        target = _target(plugin_dir)
        # Validate the bundled target before creating any profile directories.
        with _directory(target.parent) as target_fd:
            widget = _read_regular(target_fd, target.name)
            if widget is None:
                raise SetupError(f"Bundled widget does not exist: {target}")
        content = _render(target, hashlib.sha256(widget[0]).hexdigest())
        with _directory(home / "tui-widgets", create=True) as fd:
            previous = _read_regular(fd, ADAPTER_NAME, adapter=True)
            if previous is not None:
                if not _owned(previous[0], target):
                    raise SetupError("Refusing to overwrite a foreign or modified adapter")
                if previous[0] == content:
                    return _result("enable", home, False)
            _publish(fd, content, previous)
            actual = _read_regular(fd, ADAPTER_NAME, adapter=True)
            if actual is None or actual[0] != content:
                raise SetupError("Adapter publication failed readback verification")
        return _result("enable", home, True)
    except OSError as exc:
        raise SetupError(f"Unsafe or inaccessible widget path: {exc}") from exc


def disable(*, plugin_dir: str | Path | None = None) -> dict:
    """Remove only an exactly validated generated adapter; never its directory."""
    try:
        home = _home()
        target = _target(plugin_dir)
        try:
            with _directory(home / "tui-widgets") as fd:
                previous = _read_regular(fd, ADAPTER_NAME, adapter=True)
                if previous is None:
                    return _result("disable", home, False)
                if not _owned(previous[0], target):
                    raise SetupError("Refusing to remove a foreign or modified adapter")
                _same_file(fd, ADAPTER_NAME, previous)
                os.unlink(ADAPTER_NAME, dir_fd=fd)
                os.fsync(fd)
                try:
                    os.stat(ADAPTER_NAME, dir_fd=fd, follow_symlinks=False)
                except FileNotFoundError:
                    pass
                else:
                    raise SetupError("Adapter removal failed readback verification")
        except FileNotFoundError:
            return _result("disable", home, False)
        return _result("disable", home, True)
    except OSError as exc:
        raise SetupError(f"Unsafe or inaccessible widget path: {exc}") from exc


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Explicitly manage the active profile's AGY+ TUI adapter")
    parser.add_argument("action", choices=("enable", "disable"))
    parser.add_argument("--json", action="store_true", help="Return structured JSON instead of human output")
    args = parser.parse_args(argv)
    try:
        result = enable() if args.action == "enable" else disable()
    except SetupError as exc:
        if args.json:
            print(json.dumps({"ok": False, "action": args.action, "error": str(exc)}))
        else:
            print(f"Widget setup refused: {exc}", file=sys.stderr)
        return 1
    if args.json:
        print(json.dumps(result))
    else:
        state = "enabled" if args.action == "enable" else "disabled"
        status = state.capitalize() if result["changed"] else f"Already {state}"
        print(f"{status}: {result['adapter']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
